baseURL = "http://localhost:1313/"

languageCode = "en-us"
DefaultContentLanguage = "en"
title = "IA Library"
theme = "docdock"
themesdir = "themes"
pygmentsCodeFences = true
pygmentsStyle = "monokailight"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir= false
enableMissingTranslationPlaceholders = false


[params]
editURL = "https://github.com/adamcrosby/ialibrary.com/edit/master/content/"
showVisitedLinks = true # default is false
themeStyle = "flex" # "original" or "flex" # default "flex"
themeVariant = "" # choose theme variant "green", "gold" , "gray", "blue" (default)
ordersectionsby = "weight" # ordersectionsby = "title"
disableHomeIcon = false # default is false
disableSearch = false # default is false
disableNavChevron = false # set true to hide next/prev chevron, default is false
highlightClientSide = false # set true to use highlight.pack.js instead of the default hugo chroma highlighter
menushortcutsnewtab = false # set true to open shortcuts links to a new tab/window
enableGitInfo = true

[outputs]
home = [ "HTML", "RSS", "JSON"]


[[menu.shortcuts]]
name = "<i class='fa fa-fighter-jet'></i><label>NISPOM</label>"
weight = 10
#pre = "<h3>More</h3>"
url = "https://what.com"
#identifier = ""

[[menu.shortcuts]]
name = "<i class='fa fa-cloud'></i><label>Cloud</label>"
weight = 20
url = "https://what.com"

[[menu.shortcuts]]
name = "<i class='fa fa-file-contract'></i><label>DFAR</label>"
weight = 30
url = "https://what.com"

[[menu.shortcuts]]
name = "<i class='fa fa-robot'></i><label>DoD Cyber</label>"
weight = 40
url = "https://what.com"
